import os


data_path = os.path.join(os.path.abspath(os.path.dirname(os.path.dirname(__file__))), "src", "res", "survey.yaml")
plot_dir = os.path.join(os.path.abspath(os.path.dirname(os.path.dirname(__file__))), "images")

COLORS = {
    "Python": "darkgoldenrod",
    "Java": "orange",
    "JavaScript": "purple",
    "C#": "khaki",
    "C/C++": "mediumblue",
    "PHP": "indianred",
    "R": "darkorange",
    "TypeScript": "darkgreen",
    "Objective-C": "firebrick",
    "Swift": "darkred",
    "Matlab": "antiquewhite",
    "Kotlin": "tomato",
    "Go": "lightslategray",
    "Rust": "springgreen",
    "Ruby": "grey",
    "VBA": "olivedrab",
    "Ada": "blueviolet",
    "Scala": "brown",
    "Dart": "maroon",
    "Abap": "blue",
    "Visual Basic": "papayawhip",
    "Lua": "darkblue",
    "Groovy": "limegreen",
    "Perl": "lightseagreen",
    "Julia": "darkmagenta",
    "Haskell": "turquoise",
    "Cobol": "lavender",
    "React.js": "darkolivegreen",
    "jQuery": "violet",
    "Express": "bisque",
    "Angular": "navajowhite",
    "Vue.js": "greenyellow",
    "ASP.NET Core": "lightgreen",
    "Flask": "goldenrod",
    "ASP.NET": "darkslateblue",
    "Django": "lightcoral",
    "Spring": "sandybrown",
    "Angular.js": "darkgray",
    "Laravel": "mistyrose",
    "Ruby on Rails": "tan",
    "Gatsby": "rosybrown",
    "FastAPI": "saddlebrown",
    "Symfony": "lavenderblush",
    "Svelte": "cadetblue",
    "Drupal": "saddlebrown",
    "Odoo": "orange",
    "BackboneJS": "mediumseagreen",
    "OWL (Odoo Web Library)": "lightgray"
}
